{
    'name': 'Beep Import for HR Employee',
    'version': '12.0',
    'summary': 'Beep Import Excel',
    'description': """Beep Import for HR Employee""",
    'category': 'HR',
    'author': 'Emxcel Solutions',
    'website': 'https://emxcelsolutions.com/',
    'depends': ['hr', 'hr_contract', 'sale_management', 'hr_recruitment', 'hr_holidays', 'hr_timesheet',
                'hr_attendance', 'beep_hr'],
    'data': ['views/hr_attendance_views.xml',
        'views/res_company_views.xml',
        'data/hr_section_data.xml',
        # 'data/cron.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
}
