{
    'name': 'Beep Import Excel for HR',
    'version': '12.0',
    'summary': 'Beep Import Excel',
    'description': """Beep Import Excel for HR""",
    'category': 'HR',
    'author': 'Emxcel Solutions',
    'website': 'https://emxcelsolutions.com/',
    'depends': ['hr', 'hr_contract', 'sale_management', 'hr_recruitment', 'hr_holidays', 'hr_timesheet',
                'hr_attendance', 'smnl_date_format','mail'],
    'data': ['security/hr_security.xml',
             'security/ir.model.access.csv',
             'data/sequence.xml',
             'data/beep_hr_cron.xml',
             'data/beep_hr_email_template.xml',
             'views/hr_views.xml',
             'views/smnl_hr_timesheet.xml',
             'views/hr_contract_views.xml',
             'views/res_company_views.xml',
             'views/res_partner_views.xml',
             'wizard/beep_employee_import_views.xml',
             ],
    'demo': [],
    'installable': True,
    'auto_install': False,
}
