{
    'name': 'Beep Fleet management',
    'version': '12.0',
    'summary': 'Fleet Services Integration with Workshop',
    'description': """Fleet Services Integration with Workshop""",
    'category': 'Fleet',
    'author': 'Emxcel Solutions',
    'website': 'https://emxcelsolutions.com/',
    'depends': ['base', 'fleet', 'hr', 'stock', 'product', 'purchase', 'smnl_fleet_extend'],
    'data': ['security/smnl_fleet_security.xml',
             'security/ir.model.access.csv',
             'data/data.xml',
             'wizard/vehicle_delay.xml',
             'views/workshop_views.xml',
             'views/fleet_vehicle_cost_views.xml',
             'views/fleet_vehicle_views.xml',
             'views/smnl_part_product.xml',
             'views/fleet_service_type.xml',
             'views/smnl_purchase.xml',
             'views/smnl_purchase_request.xml',
             'views/smnl_inventory.xml',
             'views/smnl_gate_pass.xml',
             'report/gate_pass_report_template.xml',
             'report/gate_pass_report_action.xml'
             ],
    'demo': [],
    'installable': True,
    'auto_install': False,
}
