{
    'name': 'Beep Fleet - Return Spare parts',
    'version': '12.0',
    'summary': 'Fleet Return Spare Parts',
    'description': """Fleet Return Spare Parts""",
    'category': 'Fleet',
    'author': 'Emxcel Solutions',
    'website': 'https://emxcelsolutions.com/',
    'depends': ['base', 'fleet', 'beep_fleet', 'stock', 'product', 'purchase'],
    'data': ['security/ir.model.access.csv',
            'security/security.xml',
            'data/data.xml',
            'wizard/spare_part_returns.xml',
            'wizard/spare_reject_remarks.xml',
            'views/spare_part_returns_views.xml',
            'views/spare_part_returns_approval.xml',
            ],
    'demo': [],
    'installable': True,
    'auto_install': False,
}
